@IssueTrackerApi_HostAddress = http://localhost:1337

GET {{IssueTrackerApi_HostAddress}}/issues
Accept: application/json

###

POST {{IssueTrackerApi_HostAddress}}/issues
Content-Type: application/json

{
  "software": "Word",
  "description": "I want Clippy Back!"
}